services:
  server:
    image: ghcr.io/goauthentik/server:2026.5
    restart: unless-stopped
    container_name: authentik-server
    command: server
    shm_size: 512mb

    depends_on:
      postgresql:
        condition: service_healthy

    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: file:///run/secrets/pg_pass
      AUTHENTIK_SECRET_KEY: file:///run/secrets/secret_key
    
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.authentik.rule: Host(`authentik.xn--krver-jua.it`)
      traefik.http.routers.authentik.entrypoints: websecure
      traefik.http.routers.authentik.tls: true
      traefik.http.routers.authentik.middlewares: error-pages-middleware
      traefik.http.routers.authentik.service: authentik
      traefik.http.services.authentik.loadbalancer.server.port: 9000
    
    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/authentik/data
        target: /data
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/authentik/templates
        target: /templates

    secrets:
      - source: AUTHENTIK_SECRET_KEY
        target: secret_key
      - source: POSTGRES_PASSWORD
        target: pg_pass

    networks:
      - traefik
      - back-end


  worker:
    image: ghcr.io/goauthentik/server:2026.5
    restart: unless-stopped
    container_name: authentik-worker
    user: root
    command: worker
    shm_size: 512mb

    depends_on:
      postgresql:
        condition: service_healthy

    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__USER: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: file:///run/secrets/pg_pass
      AUTHENTIK_SECRET_KEY: file:///run/secrets/secret_key
    
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/authentik/data
        target: /data
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/authentik/templates
        target: /templates
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/authentik/certs
        target: /certs

    secrets:
      - source: AUTHENTIK_SECRET_KEY
        target: secret_key
      - source: POSTGRES_PASSWORD
        target: pg_pass

    networks:
      - back-end


  postgresql:
    image: docker.io/library/postgres:18-alpine
    restart: unless-stopped
    container_name: postgresql-authentik

    environment:
      POSTGRES_DB: authentik
      POSTGRES_USER: authentik
      POSTGRES_PASSWORD_FILE: /run/secrets/pg_pass

    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/authentik/postgresql
        target: /var/lib/postgresql/

    secrets:
      - source: POSTGRES_PASSWORD
        target: pg_pass

    networks:
      - back-end

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d authentik -U authentik"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

secrets:
  POSTGRES_PASSWORD:
    file: ${SECRETS_LOCATION:?No secrets folder configured}/${PG_PASS_FILE:?No database password file configured}
  AUTHENTIK_SECRET_KEY:
    file: ${SECRETS_LOCATION:?No secrets folder configured}/${AUTHENTIK_SECRET_KEY_FILE:?No authentik secret key file configured}

networks:
  traefik:
    external: true  
  back-end:
    internal: true