services:
  bazarr:
    image: ghcr.io/hotio/bazarr:release-1.5.6
    restart: unless-stopped
    container_name: bazarr
    hostname: bazarr.internal
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr.rule: Host(`bazarr.xn--krver-jua.it`)
      traefik.http.routers.bazarr.entrypoints: websecure
      traefik.http.routers.bazarr.tls: true
      # traefik.http.routers.bazarr.tls.certresolver: cf-dns-resolver
      traefik.http.routers.bazarr.middlewares: error-pages-middleware
    environment:
      - PUID=1108
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/bazarr
        target: /config
      - type: bind
        source: ${DATA_LOCATION:?No data directory configured}/media
        target: /data/media
        bind:
          create_host_path: true
    ports:
      - name: web-ui
        target: 6767
        published: 6767
        protocol: tcp
        app_protocol: http
        mode: host
