include:
  - jellyfin.yaml
  - seerr.yaml
  - radarr.yaml
  - sonarr.yaml
  - lidarr.yaml
  - prowlarr.yaml
  - autobrr.yaml
  - bazarr.yaml
  - qbittorrent.yaml


networks:
  default:
    name: traefik
    external: true
