services:
  jellyfin:
    image: ghcr.io/jellyfin/jellyfin:10
    restart: unless-stopped
    container_name: jellyfin
    hostname: jellyfin.internal
    user: 1101:1001

    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.jellyfin.rule: Host(`jellyfin.xn--krver-jua.it`)
      traefik.http.routers.jellyfin.entrypoints: websecure
      traefik.http.routers.jellyfin.tls: true
      traefik.http.routers.jellyfin.middlewares: error-pages-middleware
      traefik.http.routers.jellyfin.service: jellyfin
      traefik.http.services.jellyfin.loadBalancer.server.port: 8096

    environment:
      TZ: Europe/Amsterdam

    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/jellyfin/config
        target: /config
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/jellyfin/cache
        target: /cache
      - type: bind
        source: ${DATA_LOCATION:?No data directory configured}/media
        target: /data/media
        read_only: true

    networks:
      - traefik

# secrets:
  # JELLYFIN_OIDC_CLIENT_ID:
  #   file: ${SECRETS_LOCATION:?No secrets folder configured}/${JELLYFIN_OIDC_CLIENT_ID_FILE:?No OIDC client ID file configured}
  # JELLYFIN_OIDC_CLIENT_SECRET:
  #   file: ${SECRETS_LOCATION:?No secrets folder configured}/${JELLYFIN_OIDC_CLIENT_SECRET_FILE:?No OIDC client secret file configured}
  # JELLYFIN_POSTGRES_PASSWORD:
  #   file: ${SECRETS_LOCATION:?No secrets folder configured}/${JELLYFIN_PG_PASS_FILE:?No Jellyfin database password file configured}

# networks:
#   back-end_jellyfin:
#     internal: true