services:
  lidarr:
    image: ghcr.io/hotio/lidarr:release-3.1.0.4875
    restart: unless-stopped
    container_name: lidarr
    hostname: lidarr.internal

    labels:
      traefik.enable: true
      traefik.http.routers.lidarr.rule: Host(`lidarr.xn--krver-jua.it`)
      traefik.http.routers.lidarr.entrypoints: websecure
      traefik.http.routers.lidarr.tls: true
      traefik.http.routers.lidarr.middlewares: error-pages-middleware
      traefik.http.routers.lidarr.service: lidarr
      traefik.http.services.lidarr.loadBalancer.server.port: 8686

    environment:
      PUID: 1105
      PGID: 1001
      UMASK: 002
      TZ: Europe/Amsterdam

    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/lidarr
        target: /config
      - type: bind
        source: ${DATA_LOCATION:?No data directory configured}
        target: /data
        bind:
          create_host_path: true
