services:
  prowlarr:
    image: ghcr.io/hotio/prowlarr:release-2.4.0.5397
    restart: unless-stopped
    container_name: prowlarr
    hostname: prowlarr.internal

    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.rule: Host(`prowlarr.xn--krver-jua.it`)
      traefik.http.routers.prowlarr.entrypoints: websecure
      traefik.http.routers.prowlarr.tls: true
      traefik.http.routers.prowlarr.middlewares: error-pages-middleware
      traefik.http.routers.prowlarr.service: prowlarr
      traefik.http.services.prowlarr.loadBalancer.server.port: 9696

    environment:
      - PUID=1106
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam

    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/prowlarr
        target: /config
