services:
  prowlarr:
    image: ghcr.io/hotio/prowlarr:release-1.13.3.4273
    restart: unless-stopped
    container_name: prowlarr
    hostname: prowlarr.internal
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.rule: Host(`prowlarr.xn--krver-jua.it`)
      traefik.http.routers.prowlarr.entrypoints: websecure
      traefik.http.routers.prowlarr.tls: true
      # traefik.http.routers.prowlarr.tls.certresolver: cf-dns-resolver
      traefik.http.routers.prowlarr.middlewares: error-pages-middleware
    environment:
      - PUID=1106
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/prowlarr
        target: /config
    ports:
      - name: web-ui
        target: 9696
        published: 9696
        protocol: tcp
        app_protocol: http
        mode: host
