services:
  radarr:
    image: ghcr.io/hotio/radarr:release-6.3.0.10514
    restart: unless-stopped
    container_name: radarr
    hostname: radarr.internal

    labels:
      traefik.enable: true
      traefik.http.routers.radarr.rule: Host(`radarr.xn--krver-jua.it`)
      traefik.http.routers.radarr.entrypoints: websecure
      traefik.http.routers.radarr.tls: true
      traefik.http.routers.radarr.middlewares: error-pages-middleware
      traefik.http.routers.radarr.service: radarr
      traefik.http.services.radarr.loadBalancer.server.port: 7878

    environment:
      - PUID=1103
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam

    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/radarr
        target: /config
      - type: bind
        source: ${DATA_LOCATION:?No data directory configured}
        target: /data
        bind:
          create_host_path: true
