services:
  seerr:
    image: ghcr.io/hotio/seerr:release-3.3.0
    restart: unless-stopped
    container_name: seerr
    hostname: seerr.internal
    labels:
      traefik.enable: true
      traefik.http.routers.seerr.rule: Host(`seerr.xn--krver-jua.it`)
      traefik.http.routers.seerr.entrypoints: websecure
      traefik.http.routers.seerr.tls: true
      # traefik.http.routers.seerr.tls.certresolver: cf-dns-resolver
      traefik.http.routers.seerr.middlewares: error-pages-middleware
    environment:
      - PUID=1102
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/seerr
        target: /config
    ports:
      - name: web-ui
        target: 5055
        published: 5055
        protocol: tcp
        app_protocol: http
        mode: host