services:
  seerr:
    image: ghcr.io/hotio/seerr:release-v3
    restart: unless-stopped
    container_name: seerr
    hostname: seerr.internal

    labels:
      traefik.enable: true
      traefik.http.routers.seerr.rule: Host(`seerr.xn--krver-jua.it`)
      traefik.http.routers.seerr.entrypoints: websecure
      traefik.http.routers.seerr.tls: true
      traefik.http.routers.seerr.middlewares: error-pages-middleware
      traefik.http.routers.seerr.service: seerr
      traefik.http.services.seerr.loadBalancer.server.port: 5055

    environment:
      PUID: 1102
      PGID: 1001
      UMASK: 002
      TZ: Europe/Amsterdam

    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/seerr
        target: /config