services:
  seerr:
    image: ghcr.io/seerr-team/seerr:v3
    restart: unless-stopped
    init: true
    container_name: seerr
    hostname: seerr.internal

    depends_on:
      postgresql-seerr:
        condition: service_healthy

    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.seerr.rule: Host(`seerr.xn--krver-jua.it`)
      traefik.http.routers.seerr.entrypoints: websecure
      traefik.http.routers.seerr.tls: true
      traefik.http.routers.seerr.middlewares: error-pages-middleware
      traefik.http.routers.seerr.service: seerr
      traefik.http.services.seerr.loadBalancer.server.port: 5055

    environment:
      TZ: Europe/Amsterdam

      # Database
      DB_TYPE: postgres
      DB_HOST: postgresql-seerr
      DB_PORT: "5432"
      DB_NAME: seerr
      DB_USER: seerr
      DB_PASS: ${SEERR_PG_PASS:?No Seerr database password configured}

    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/seerr/config
        target: /app/config

    networks:
      - traefik
      - back-end_seerr

    healthcheck:
      test: [
        "CMD",
        "wget",
        "--no-verbose",
        "--tries=1",
        "--spider",
        "http://127.0.0.1:5055/api/v1/settings/public"
        ]
      interval: 15s
      timeout: 3s
      retries: 3
      start_period: 20s


  postgresql-seerr:
    image: docker.io/library/postgres:18-alpine
    restart: unless-stopped
    container_name: postgresql-seerr

    environment:
      POSTGRES_DB: seerr
      POSTGRES_USER: seerr
      POSTGRES_PASSWORD: ${SEERR_PG_PASS:?No Seerr database password configured}

    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/seerr/postgresql
        target: /var/lib/postgresql/

    networks:
      - back-end_seerr

    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -q --username \"$${POSTGRES_USER}\" --dbname postgres"
        ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s


# secrets:
  # SEERR_OIDC_CLIENT_ID:
  #   file: ${SECRETS_LOCATION:?No secrets folder configured}/${SEERR_OIDC_CLIENT_ID_FILE:?No OIDC client ID file configured}
  # SEERR_OIDC_CLIENT_SECRET:
  #   file: ${SECRETS_LOCATION:?No secrets folder configured}/${SEERR_OIDC_CLIENT_SECRET_FILE:?No OIDC client secret file configured}
  # SEERR_POSTGRES_PASSWORD:
  #   file: ${SECRETS_LOCATION:?No secrets folder configured}/${SEERR_PG_PASS_FILE:?No Seerr database password file configured}


networks:
  back-end_seerr:
    internal: true
