services:
  sonarr:
    image: ghcr.io/hotio/sonarr:release-4.0.17.2952
    restart: unless-stopped
    container_name: sonarr
    hostname: sonarr.internal
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.rule: Host(`sonarr.xn--krver-jua.it`)
      traefik.http.routers.sonarr.entrypoints: websecure
      traefik.http.routers.sonarr.tls: true
      # traefik.http.routers.sonarr.tls.certresolver: cf-dns-resolver
      traefik.http.routers.sonarr.middlewares: error-pages-middleware
    environment:
      - PUID=1104
      - PGID=1001
      - UMASK=002
      - TZ=Europe/Amsterdam
    volumes:
      - type: bind
        source: ${APPDATA_LOCATION:?No appdata directory configured}/sonarr
        target: /config
      - type: bind
        source: ${DATA_LOCATION:?No data directory configured}
        target: /data
        bind:
          create_host_path: true
    ports:
      - name: web-ui
        target: 8989
        published: 8989
        protocol: tcp
        app_protocol: http
        mode: host
